import os
import glob
import re
from collections import defaultdict
from poke_env import to_id_str
import src.constants as constants

TEAMS_DIR = os.path.join(os.path.dirname(__file__), "..", "teams")
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "item_priors.py")

def clean_species_name(name_part: str) -> str:
    """Extracts base species ID, removing gender flags, nicknames, and mega tags."""
    # Strip gender tag "(M)" or "(F)"
    name_part = re.sub(r"\s*\([MF]\)$", "", name_part.strip())

    # Extract species from parenthesis if nicknamed
    match = re.search(r"\(([^)]+)\)$", name_part)
    raw_species = match.group(1).strip() if match else name_part.strip()

    showdown_id = to_id_str(raw_species)

    for suffix in ["megax", "megay", "megaz", "mega"]:
        if showdown_id.endswith(suffix) and len(showdown_id) > len(suffix):
            base = showdown_id[:-len(suffix)]
            if base in constants.BASE_TO_MEGA_STONE:
                return base

    return showdown_id

def generate_item_priors():
    team_files = sorted(glob.glob(os.path.join(TEAMS_DIR, "*.txt")))
    print(f"Found {len(team_files)} team files in {TEAMS_DIR}.")

    counts = defaultdict(lambda: defaultdict(int))
    total_mons = 0

    for file_path in team_files:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read().strip()

        # Split pokepaste into individual Pokemon blocks
        blocks = [b.strip() for b in content.split("\n\n") if b.strip()]

        for block in blocks:
            first_line = block.split("\n")[0].strip()

            if "@" in first_line:
                name_part, item_part = first_line.split("@", 1)
                item_id = to_id_str(item_part)
            else:
                name_part = first_line
                item_id = "no_item"

            species_id = clean_species_name(name_part)

            # Validate item against ITEM_TO_IDX
            if item_id not in constants.ITEM_TO_IDX:
                print(f"Warning: Unknown item '{item_id}' on {species_id} in {os.path.basename(file_path)}")
                continue

            counts[species_id][item_id] += 1
            total_mons += 1

    priors = {}
    for species, item_dict in sorted(counts.items()):
        total = sum(item_dict.values())
        # Sort items by highest probability first
        sorted_items = sorted(item_dict.items(), key=lambda x: x[1], reverse=True)
        priors[species] = {
            item: round(cnt / total, 4) for item, cnt in sorted_items
        }

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("# Automatically generated by src/generate_item_priors.py\n")
        f.write("# Do not edit manually.\n\n")
        f.write("ITEM_PRIORS = {\n")
        for species, p_dict in priors.items():
            f.write(f'    "{species}": {{\n')
            for item, prob in p_dict.items():
                f.write(f'        "{item}": {prob},\n')
            f.write("    },\n")
        f.write("}\n")

generate_item_priors()