# Automatically generated by src/generate_item_priors.py
# Do not edit manually.

ITEM_PRIORS = {
    "absol": {
        "absolitez": 1.0,
    },
    "aerodactyl": {
        "focussash": 1.0,
    },
    "altaria": {
        "habanberry": 1.0,
    },
    "annihilape": {
        "choicescarf": 1.0,
    },
    "arcaninehisui": {
        "focussash": 1.0,
    },
    "archaludon": {
        "leftovers": 1.0,
    },
    "armarouge": {
        "lifeorb": 0.5,
        "leftovers": 0.25,
        "twistedspoon": 0.25,
    },
    "basculegion": {
        "lifeorb": 0.4,
        "choicescarf": 0.4,
        "mysticwater": 0.2,
    },
    "blastoise": {
        "blastoisinite": 1.0,
    },
    "camerupt": {
        "cameruptite": 1.0,
    },
    "ceruledge": {
        "colburberry": 0.3333,
        "focussash": 0.3333,
        "grassyseed": 0.3333,
    },
    "charizard": {
        "charizarditey": 1.0,
    },
    "corviknight": {
        "psychicseed": 1.0,
    },
    "delphox": {
        "delphoxite": 1.0,
    },
    "dragapult": {
        "lifeorb": 1.0,
    },
    "dragonite": {
        "dragoninite": 0.6,
        "lifeorb": 0.4,
    },
    "excadrill": {
        "focussash": 1.0,
    },
    "farigiraf": {
        "sitrusberry": 0.375,
        "colburberry": 0.25,
        "grassyseed": 0.125,
        "twistedspoon": 0.125,
        "lifeorb": 0.125,
    },
    "floetteeternal": {
        "floettite": 1.0,
    },
    "floettemega": {
        "floettite": 1.0,
    },
    "froslass": {
        "froslassite": 1.0,
    },
    "garchomp": {
        "garchompitez": 0.5,
        "choicescarf": 0.3333,
        "lifeorb": 0.1667,
    },
    "gardevoir": {
        "gardevoirite": 1.0,
    },
    "gengar": {
        "gengarite": 1.0,
    },
    "gholdengo": {
        "lifeorb": 0.9459,
        "whiteherb": 0.027,
        "leftovers": 0.027,
    },
    "glimmora": {
        "glimmoranite": 0.6667,
        "focussash": 0.3333,
    },
    "golisopod": {
        "golisopite": 1.0,
    },
    "grimmsnarl": {
        "lightclay": 1.0,
    },
    "hatterene": {
        "lifeorb": 1.0,
    },
    "hippowdon": {
        "leftovers": 1.0,
    },
    "hydreigon": {
        "focussash": 1.0,
    },
    "incineroar": {
        "sitrusberry": 0.7714,
        "passhoberry": 0.0857,
        "rockyhelmet": 0.0857,
        "chopleberry": 0.0571,
    },
    "indeedee": {
        "focussash": 0.5,
        "choicescarf": 0.5,
    },
    "indeedeef": {
        "rockyhelmet": 0.5833,
        "colburberry": 0.3333,
        "focussash": 0.0833,
    },
    "kingambit": {
        "chopleberry": 0.5625,
        "lifeorb": 0.1875,
        "focussash": 0.125,
        "blackglasses": 0.125,
    },
    "kommoo": {
        "leftovers": 0.75,
        "lifeorb": 0.25,
    },
    "lopunny": {
        "lopunnite": 1.0,
    },
    "lucario": {
        "lucarionitez": 1.0,
    },
    "mausholdfour": {
        "widelens": 1.0,
    },
    "mawile": {
        "mawilite": 1.0,
    },
    "metagross": {
        "metagrossite": 1.0,
    },
    "milotic": {
        "sitrusberry": 0.5,
        "leftovers": 0.3333,
        "psychicseed": 0.1667,
    },
    "ninetalesalola": {
        "choicescarf": 1.0,
    },
    "noivern": {
        "focussash": 1.0,
    },
    "pawmot": {
        "focussash": 1.0,
    },
    "pelipper": {
        "focussash": 0.5455,
        "sitrusberry": 0.3636,
        "lifeorb": 0.0909,
    },
    "politoed": {
        "sitrusberry": 0.5,
        "mysticwater": 0.25,
        "ejectbutton": 0.25,
    },
    "primarina": {
        "grassyseed": 0.5,
        "leftovers": 0.25,
        "lifeorb": 0.25,
    },
    "pyroar": {
        "pyroarite": 1.0,
    },
    "raichu": {
        "raichunitey": 1.0,
    },
    "rillaboom": {
        "miracleseed": 0.7455,
        "sitrusberry": 0.0909,
        "ejectbutton": 0.0727,
        "expertbelt": 0.0364,
        "occaberry": 0.0364,
        "lifeorb": 0.0182,
    },
    "salamence": {
        "salamencite": 1.0,
    },
    "scrafty": {
        "focussash": 1.0,
    },
    "sinistcha": {
        "sitrusberry": 0.6667,
        "rockyhelmet": 0.3333,
    },
    "sinistchamasterpiece": {
        "colburberry": 1.0,
    },
    "sirfetchâd": {
        "expertbelt": 1.0,
    },
    "sneasler": {
        "grassyseed": 0.4848,
        "whiteherb": 0.303,
        "psychicseed": 0.1515,
        "focussash": 0.0606,
    },
    "snorlax": {
        "leftovers": 1.0,
    },
    "squawkabilly": {
        "choicescarf": 1.0,
    },
    "staraptor": {
        "staraptite": 1.0,
    },
    "swampert": {
        "swampertite": 1.0,
    },
    "sylveon": {
        "fairyfeather": 1.0,
    },
    "talonflame": {
        "sharpbeak": 1.0,
    },
    "torkoal": {
        "charcoal": 0.6667,
        "lifeorb": 0.3333,
    },
    "toxapex": {
        "leftovers": 1.0,
    },
    "tyranitar": {
        "tyranitarite": 0.8571,
        "chopleberry": 0.1429,
    },
    "venusaur": {
        "focussash": 0.6667,
        "widelens": 0.3333,
    },
    "volcarona": {
        "grassyseed": 0.5,
        "rockyhelmet": 0.5,
    },
    "whimsicott": {
        "focussash": 1.0,
    },
}
